#!/bin/bash

mpirun -np * liggghts < in1.MgO_proporcion_muMU_sigmaSIGMA
mpirun -np * liggghts < in2.MgO_proporcion_muMU_sigmaSIGMA
mpirun -np * liggghts < in3.MgO_proporcion_muMU_sigmaSIGMA
mpirun -np * liggghts < in4.MgO_proporcion_muMU_sigmaSIGMA